---
title: "Analisis"
author: "Jannik Hannemann"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(conflicted)
library(ggplot2)
library(here)
library(ggrepel)

conflicts_prefer(dplyr::filter)
conflicts_prefer(dplyr::lag)
```


```{r Environmental data}
data <- read_csv2(here("2025-02-07 Datos ambientales PIM.csv"))

graph_data <- data %>% 
  group_by(Ubicación) %>%
  summarise(
    `Temperatura media` = mean(`Temperatura`, na.rm = TRUE),
    `Temperatura desviación típica` = sd(`Temperatura`, na.rm = TRUE),
    `Humedad media` = mean(`Humedad`, na.rm = TRUE),
    `Humedad desviación típica` = sd(`Humedad`, na.rm = TRUE),
  )
graph_data %>% 
  ggplot(aes(y = `Temperatura media`, x = `Ubicación`, fill = Ubicación)) +
  geom_col() + 
  ylab("Temperatura media en °C") +
  ggtitle("Temperatura media por ubicación con la desviación típica") +
  theme(plot.title = element_text(hjust = 0.5), legend.position = "none") +
  coord_cartesian(ylim = c(10.5, 14)) +
  geom_errorbar(aes(ymin = `Temperatura media` - `Temperatura desviación típica`, 
                ymax = `Temperatura media` + `Temperatura desviación típica`), 
                width = 0.2, position = position_dodge(0.9))
  
graph_data %>%
  ggplot(aes(y = `Humedad media` * 100, x = `Ubicación`, fill = Ubicación)) +
  geom_col() + 
  ylab("Humedad media en %") +
  ggtitle("Humedad media por ubicación con la desviación típica") +
  theme(plot.title = element_text(hjust = 0.5), legend.position = "none") +
  coord_cartesian(ylim = c(0, 35)) +
  geom_errorbar(aes(ymin = (`Humedad media` - `Humedad desviación típica`) * 100, 
                ymax = (`Humedad media` + `Humedad desviación típica`) * 100) , 
                width = 0.2, position = position_dodge(0.9))

```



```{r}
data2 <- read.csv2(here("2025-04-08 - datos especies - medias.csv"), fileEncoding = "UTF-8")

graph_data2 <- data2 %>% 
  mutate(Especie = substring(Especie, 1, nchar(Especie) - 2)) %>% 
  group_by(Especie) %>% 
  summarise(
    `Olivo` = sum(Olivo, na.rm = TRUE),
    `Entreolivo` = sum(Entreolivo, na.rm = TRUE),
    `Prado` = sum(Prado, na.rm = TRUE),
  ) %>% 
  arrange(desc(Olivo))

OlivoPosData <- graph_data2 %>%
  filter(Olivo > 0) %>%
  mutate(csum = rev(cumsum(rev(Olivo))), 
         Olypos = Olivo/2 + lead(csum, 1),
         Olypos = if_else(is.na(Olypos), Olivo/2, Olypos))

EntreOlivoPosData <- graph_data2 %>%
  filter(Entreolivo > 0) %>%
  mutate(csum = rev(cumsum(rev(Entreolivo))), 
         EntreOlypos = Entreolivo/2 + lead(csum, 1),
         EntreOlypos = if_else(is.na(EntreOlypos), Entreolivo/2, EntreOlypos))

PradoPosData <- graph_data2 %>%
  filter(Prado > 0) %>%
  mutate(csum = rev(cumsum(rev(Prado))), 
         Pradoypos = Prado/2 + lead(csum, 1),
         Pradoypos = if_else(is.na(Pradoypos), Prado/2, Pradoypos))
```

``` {r}
graph_data2 %>% 
  ggplot(aes(x="", y=Olivo, fill=fct_inorder(Especie))) +
  geom_bar(stat="identity", width=1, color="white") +
  coord_polar("y", start=0) +
  geom_label_repel(data = OlivoPosData,
                   aes(y = Olypos, label = paste0(Especie)),
                   size = 4.5, nudge_x = 1, show.legend = FALSE) +
  theme_void() + 
  theme(legend.position = "none", plot.margin = margin(t = 10, r = 0, b = 0, l = 0, unit = "pt"))
```

```{r}
graph_data2 %>% 
  ggplot(aes(x="", y=Prado, fill=fct_inorder(Especie))) +
  geom_bar(stat="identity", width=1, color="white") +
  coord_polar("y", start=0) +
  geom_label_repel(data = PradoPosData,
                   aes(y = Pradoypos, label = paste0(Especie)),
                   size = 4.5, nudge_x = 1, show.legend = FALSE) +
  theme_void() + 
  theme(legend.position = "none", plot.margin = margin(t = 10, r = 0, b = 0, l = 0, unit = "pt"))
```

```{r}
graph_data2 %>% 
  ggplot(aes(x="", y=Entreolivo, fill=fct_inorder(Especie))) +
  geom_bar(stat="identity", width=1, color="white") +
  coord_polar("y", start=0) +
  geom_label_repel(data = EntreOlivoPosData,
                   aes(y = EntreOlypos, label = paste0(Especie)),
                   size = 4.5, nudge_x = 1, show.legend = FALSE) +
  theme_void() + 
  theme(legend.position = "none", plot.margin = margin(t = 10, r = 0, b = 0, l = 0, unit = "pt"))

```

